config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'todos/index', as: 'todos_index'
  get 'tasks/index'
  get 'todos/:id', to: 'todos#show', as: 'todos_show'
  patch 'todos/:id', to: 'todos#update', as: 'todos_update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "tasks#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :todos
  has_many :users, through: :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :todos
    has_many :tasks, through: :todos
    after_create :load_todos

    private

    def load_todos
      Task.all.each do |task|
        Todo.create(user: self, task: task)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks=Task.all
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :progress
  def index
    @todos = current_user.todos
  end

  def update
    @todo=Todo.find(params[:id])
    @todo.status = !@todo.status
    @todo.save
    redirect_to todos_index_path
  end

  def show
      @todo=Todo.find(params[:id])
      @todos= Todo.where(task: @todo.task, status: true)
  end

private
def progress
  @todos_count = current_user.todos.where(status: true).count
  @all_todos = current_user.todos.count
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fiestas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'sharred/navbar' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/sharred/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand pr-4" >Bucket list of 18°   </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">

    <% if user_signed_in?%>
    <ul class="navbar-nav">
      <li class="nav-item active pr-1">
        <%= @todos_count %>
      </li>
      <li class="nav-item active ">
        <%= '/' %>
      </li>
      <li class="nav-item active pr-1">
        <%= @all_todos %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Cerrar_sesion', destroy_user_session_path, method: :delete %>
      </li>
  </ul>
    <% end %>


  </div>
</nav>

app/views/tasks/index.html.erb
<% @tasks.each_slice(3) do |task2|%>
<div class="card-deck">
   <% task2.each do |task|%>
  <div class="card m-4 p-4">
  <%=  image_tag task.photo, class: 'card-image-top img-fluid', style: 'height:250px;width:250px', style: "filter: grayscale(100%)" %>

    <div class="card-body">
      <h5 class="card-title"> <%=task.name %></h5>

      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>

        <%=link_to "listo", todos_index_path, class: "btn btn-outline-danger" %>



  </div>
    <%end%>
</div>
  <%end%>

app/views/todos/index.html.erb
<% @todos.each_slice(3) do |todo2|%>
<div class="card-deck">
   <% todo2.each do |todo|%>
  <div class="card m-4 p-4">
  <% if todo.status == true %>
    <%=  image_tag todo.task.photo, class: 'card-image-top img-fluid', style: 'height:250px;width:250px' %>
<% else %>
  <%=  image_tag todo.task.photo, class: 'card-image-top img-fluid', style: 'height:250px;width:250px', style: "filter: grayscale(100%)" %>
  <%end%>
    <div class="card-body">
      <h5 class="card-title"> <%=todo.task.name %></h5>
  <%=link_to "ver detalle",todos_show_path(todo), class:"btn btn-success" %>
    </div>
    <% if todo.status == true %>
        <%=link_to "listo", todos_update_path(todo), method: :patch, class:"btn btn-outline-success" %>
        <% else %>
        <%=link_to "no listo",todos_update_path(todo), method: :patch, class:"btn btn-outline-danger" %>
        <% end %>


  </div>
    <%end%>
</div>
  <%end%>

app/views/todos/show.html.erb
  <div class="card m-4 p-4">
    <%= link_to 'Back', todos_index_path %>
    <br>
      <div class="card-body">
  <% if @todo.status == true %>
    <%=  image_tag @todo.task.photo, class: 'card-image-top img-fluid', style: 'height:250px,width:250px' %>
<% else %>
  <%=  image_tag @todo.task.photo, class: 'card-image-top img-fluid', style: 'height:250px,width:250px', style: "filter: grayscale(100%)" %>
  <%end%>

      <h5 class="card-title"> <%=@todo.task.name %></h5>
  </div>
</div>
<% @todos.each do |todo| %>
<%= todo.user.name %>
<% end %>